<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname(dirname($vendorDir))).'/default/files/composer';

return array(
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Neutron' => array($vendorDir . '/neutron/temporary-filesystem/src'),
    'Guzzle\\Tests' => array($vendorDir . '/guzzle/guzzle/tests'),
    'Guzzle' => array($vendorDir . '/guzzle/guzzle/src'),
    'FFMpeg' => array($vendorDir . '/php-ffmpeg/php-ffmpeg/src'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Aws' => array($vendorDir . '/aws/aws-sdk-php/src'),
    'Alchemy' => array($vendorDir . '/alchemy/binary-driver/src'),
);
